In [3]:
import pandas as pd
import numpy as np
from faker import Faker
import random

print("Everything installed successfully!")

Everything installed successfully!

In [4]:
fake = Faker('en_IN')

In [5]:
casts = [
    "General",
    "OBC",
    "SC",
    "ST",
    "EWS"
]

subjects = [
    "English",
    "Maths",
    "Biology",
    "Chemistry",
    "Physics",
    "Computer Applications"
]

In [6]:
students = []

In [ ]:
for i in range(1, 101):
    
    student = {

        "Roll_Number": f"2026CS{i:03}",

        "Student_Name": fake.name(),

        "English": random.randint(35, 100),

        "Maths": random.randint(35, 100),

        "Biology": random.randint(35, 100),

        "Chemistry": random.randint(35, 100),

        "Physics": random.randint(35, 100),

        "Computer_Applications": random.randint(35, 100),

        "Attendance": random.randint(50, 100),

        "Date_of_Birth": fake.date_of_birth(
            minimum_age=17,
            maximum_age=22
        ),

        "Phone_Number": fake.phone_number(),

        "Caste": random.choice(casts),

        "Father_Name": fake.name_male(),

        "Mother_Name": fake.name_female(),

        "Family_Income_Per_Annum":
            random.randint(100000, 2000000),

        "Address":
            fake.address().replace("\n", ", ")
    }

    students.append(student)

In [15]:
df = pd.DataFrame(students)

In [17]:
df.head()

,Roll_Number,Student_Name,English,Maths,Biology,Chemistry,Physics,Computer_Applications,Attendance,Date_of_Birth,Phone_Number,Caste,Father_Name,Mother_Name,Family_Income_Per_Annum,Address
0,2026CS001,Kiaan Chakraborty,69,93,50,97,37,68,56,2008-12-14,3783359388,EWS,Chatura Parekh,Yadavi Gola,1623755,"H.No. 63, Swamy, Vijayanagaram 250857"
1,2026CS002,Tripti Cherian,68,62,74,39,71,48,85,2008-07-06,+915525393650,General,Bakhshi Wali,Dhriti Mann,1851649,"03, Om Street, Bathinda-243852"
2,2026CS003,Ria Chahal,98,74,69,89,87,36,79,2006-01-05,+913599880666,EWS,Ayush Bhargava,Anjali Das,958184,"022, Doshi Road, Durgapur 646873"
3,2026CS004,Adya Kade,45,55,42,83,49,71,73,2004-02-04,04235814550,SC,Gopal Munshi,Upadhriti Chaudhary,149863,"H.No. 525, Karan Road, Bidhannagar-413976"
4,2026CS005,Kabir Lata,94,40,46,76,89,43,96,2005-01-03,+917272218871,EWS,Faris Bakshi,Charita Sankar,988679,"H.No. 073, Murty Ganj, Hospet-550468"

In [10]:
len(df)

100

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Roll_Number              100 non-null    object
 1   Student_Name             100 non-null    object
 2   English                  100 non-null    int64
 3   Maths                    100 non-null    int64
 4   Biology                  100 non-null    int64
 5   Chemistry                100 non-null    int64
 6   Physics                  100 non-null    int64
 7   Computer_Applications    100 non-null    int64
 8   Attendance               100 non-null    int64
 9   Date_of_Birth            100 non-null    object
 10  Phone_Number             100 non-null    object
 11  Caste                    100 non-null    object
 12  Father_Name              100 non-null    object
 13  Mother_Name              100 non-null    object
 14  Family_Income_Per_Annum  100 non-null    int64
 15  Address                  100 non-null    object
dtypes: int64(8), object(8)
memory usage: 12.6+ KB

In [12]:
df.isnull().sum()

Roll_Number                0
Student_Name               0
English                    0
Maths                      0
Biology                    0
Chemistry                  0
Physics                    0
Computer_Applications      0
Attendance                 0
Date_of_Birth              0
Phone_Number               0
Caste                      0
Father_Name                0
Mother_Name                0
Family_Income_Per_Annum    0
Address                    0
dtype: int64

In [13]:
df.to_csv("academic_dataset.csv", index=False)

print("Dataset Saved Successfully")

Dataset Saved Successfully

In [18]:
pd.read_csv("academic_dataset.csv")

,Roll_Number,Student_Name,English,Maths,Biology,Chemistry,Physics,Computer_Applications,Attendance,Date_of_Birth,Phone_Number,Caste,Father_Name,Mother_Name,Family_Income_Per_Annum,Address
0,2026CS001,Kiaan Chakraborty,69,93,50,97,37,68,56,2008-12-14,3783359388,EWS,Chatura Parekh,Yadavi Gola,1623755,"H.No. 63, Swamy, Vijayanagaram 250857"
1,2026CS002,Tripti Cherian,68,62,74,39,71,48,85,2008-07-06,915525393650,General,Bakhshi Wali,Dhriti Mann,1851649,"03, Om Street, Bathinda-243852"
2,2026CS003,Ria Chahal,98,74,69,89,87,36,79,2006-01-05,913599880666,EWS,Ayush Bhargava,Anjali Das,958184,"022, Doshi Road, Durgapur 646873"
3,2026CS004,Adya Kade,45,55,42,83,49,71,73,2004-02-04,4235814550,SC,Gopal Munshi,Upadhriti Chaudhary,149863,"H.No. 525, Karan Road, Bidhannagar-413976"
4,2026CS005,Kabir Lata,94,40,46,76,89,43,96,2005-01-03,917272218871,EWS,Faris Bakshi,Charita Sankar,988679,"H.No. 073, Murty Ganj, Hospet-550468"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2026CS096,Dayamai Munshi,39,89,82,79,67,69,60,2008-06-15,4283224179,OBC,Chandran Lata,Ishanvi Uppal,1325398,"H.No. 35, Garde Path, Firozabad 236032"
96,2026CS097,Harish Chaudhari,39,51,77,86,46,63,73,2008-07-24,8795650367,OBC,Ayushman Narasimhan,Oviya Chanda,1182715,"96/448, Buch Zila, Mahbubnagar 591416"
97,2026CS098,Gayathri Chokshi,72,49,46,55,77,86,68,2003-07-15,918250234195,OBC,Yatan Gopal,Panini Dhar,1437750,"H.No. 63, Narula Nagar, Saharsa 817429"
98,2026CS099,Ethan Sinha,66,74,92,72,90,94,81,2005-03-11,7524712467,SC,Matthew Hora,Aarini Kaul,875156,"73/76, Kalita Ganj, Begusarai-239773"
99,2026CS100,Bhavya Kakar,61,61,35,53,63,66,73,2004-06-09,1205467428,OBC,Patrick Grover,Warda Nanda,1708256,"81, Dara Chowk, Kollam 692540"

In [19]:
df["Roll_Number"] = range(100, 200)

df.head()

ValueError: Length of values (100) does not match length of index (200)

In [20]:
len(df)

200

In [21]:
df.shape

(200, 16)

In [22]:
df["Roll_Number"] = range(100, 300)

In [23]:
df = df.head(100)

In [24]:
df["Roll_Number"] = range(100, 200)

C:\Users\PRIYABRATA PANJA\AppData\Local\Temp\ipykernel_17636\4237486861.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Roll_Number"] = range(100, 200)

In [25]:
df.head()

,Roll_Number,Student_Name,English,Maths,Biology,Chemistry,Physics,Computer_Applications,Attendance,Date_of_Birth,Phone_Number,Caste,Father_Name,Mother_Name,Family_Income_Per_Annum,Address
0,100,Kiaan Chakraborty,69,93,50,97,37,68,56,2008-12-14,3783359388,EWS,Chatura Parekh,Yadavi Gola,1623755,"H.No. 63, Swamy, Vijayanagaram 250857"
1,101,Tripti Cherian,68,62,74,39,71,48,85,2008-07-06,+915525393650,General,Bakhshi Wali,Dhriti Mann,1851649,"03, Om Street, Bathinda-243852"
2,102,Ria Chahal,98,74,69,89,87,36,79,2006-01-05,+913599880666,EWS,Ayush Bhargava,Anjali Das,958184,"022, Doshi Road, Durgapur 646873"
3,103,Adya Kade,45,55,42,83,49,71,73,2004-02-04,04235814550,SC,Gopal Munshi,Upadhriti Chaudhary,149863,"H.No. 525, Karan Road, Bidhannagar-413976"
4,104,Kabir Lata,94,40,46,76,89,43,96,2005-01-03,+917272218871,EWS,Faris Bakshi,Charita Sankar,988679,"H.No. 073, Murty Ganj, Hospet-550468"

In [26]:
df.to_csv("academic_dataset.csv", index=False)

pd.read_csv("academic_dataset.csv").head()

,Roll_Number,Student_Name,English,Maths,Biology,Chemistry,Physics,Computer_Applications,Attendance,Date_of_Birth,Phone_Number,Caste,Father_Name,Mother_Name,Family_Income_Per_Annum,Address
0,100,Kiaan Chakraborty,69,93,50,97,37,68,56,2008-12-14,3783359388,EWS,Chatura Parekh,Yadavi Gola,1623755,"H.No. 63, Swamy, Vijayanagaram 250857"
1,101,Tripti Cherian,68,62,74,39,71,48,85,2008-07-06,915525393650,General,Bakhshi Wali,Dhriti Mann,1851649,"03, Om Street, Bathinda-243852"
2,102,Ria Chahal,98,74,69,89,87,36,79,2006-01-05,913599880666,EWS,Ayush Bhargava,Anjali Das,958184,"022, Doshi Road, Durgapur 646873"
3,103,Adya Kade,45,55,42,83,49,71,73,2004-02-04,4235814550,SC,Gopal Munshi,Upadhriti Chaudhary,149863,"H.No. 525, Karan Road, Bidhannagar-413976"
4,104,Kabir Lata,94,40,46,76,89,43,96,2005-01-03,917272218871,EWS,Faris Bakshi,Charita Sankar,988679,"H.No. 073, Murty Ganj, Hospet-550468"

In [27]:
df.to_csv("academic_dataset.csv", index=False)

In [28]:
df.to_csv("academic_dataset.csv", index=False)

pd.read_csv("academic_dataset.csv").head()

,Roll_Number,Student_Name,English,Maths,Biology,Chemistry,Physics,Computer_Applications,Attendance,Date_of_Birth,Phone_Number,Caste,Father_Name,Mother_Name,Family_Income_Per_Annum,Address
0,100,Kiaan Chakraborty,69,93,50,97,37,68,56,2008-12-14,3783359388,EWS,Chatura Parekh,Yadavi Gola,1623755,"H.No. 63, Swamy, Vijayanagaram 250857"
1,101,Tripti Cherian,68,62,74,39,71,48,85,2008-07-06,915525393650,General,Bakhshi Wali,Dhriti Mann,1851649,"03, Om Street, Bathinda-243852"
2,102,Ria Chahal,98,74,69,89,87,36,79,2006-01-05,913599880666,EWS,Ayush Bhargava,Anjali Das,958184,"022, Doshi Road, Durgapur 646873"
3,103,Adya Kade,45,55,42,83,49,71,73,2004-02-04,4235814550,SC,Gopal Munshi,Upadhriti Chaudhary,149863,"H.No. 525, Karan Road, Bidhannagar-413976"
4,104,Kabir Lata,94,40,46,76,89,43,96,2005-01-03,917272218871,EWS,Faris Bakshi,Charita Sankar,988679,"H.No. 073, Murty Ganj, Hospet-550468"

In [29]:
df.reset_index(drop=True, inplace=True)
df.head()

,Roll_Number,Student_Name,English,Maths,Biology,Chemistry,Physics,Computer_Applications,Attendance,Date_of_Birth,Phone_Number,Caste,Father_Name,Mother_Name,Family_Income_Per_Annum,Address
0,100,Kiaan Chakraborty,69,93,50,97,37,68,56,2008-12-14,3783359388,EWS,Chatura Parekh,Yadavi Gola,1623755,"H.No. 63, Swamy, Vijayanagaram 250857"
1,101,Tripti Cherian,68,62,74,39,71,48,85,2008-07-06,+915525393650,General,Bakhshi Wali,Dhriti Mann,1851649,"03, Om Street, Bathinda-243852"
2,102,Ria Chahal,98,74,69,89,87,36,79,2006-01-05,+913599880666,EWS,Ayush Bhargava,Anjali Das,958184,"022, Doshi Road, Durgapur 646873"
3,103,Adya Kade,45,55,42,83,49,71,73,2004-02-04,04235814550,SC,Gopal Munshi,Upadhriti Chaudhary,149863,"H.No. 525, Karan Road, Bidhannagar-413976"
4,104,Kabir Lata,94,40,46,76,89,43,96,2005-01-03,+917272218871,EWS,Faris Bakshi,Charita Sankar,988679,"H.No. 073, Murty Ganj, Hospet-550468"

In [30]:
bangalore_addresses = [
    "Koramangala, Bangalore",
    "Indiranagar, Bangalore",
    "Whitefield, Bangalore",
    "Jayanagar, Bangalore",
    "BTM Layout, Bangalore",
    "Electronic City, Bangalore",
    "Marathahalli, Bangalore",
    "HSR Layout, Bangalore",
    "Rajajinagar, Bangalore",
    "Yelahanka, Bangalore"
]

df["Address"] = [random.choice(bangalore_addresses) for _ in range(len(df))]

df.head()

C:\Users\PRIYABRATA PANJA\AppData\Local\Temp\ipykernel_17636\393000489.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Address"] = [random.choice(bangalore_addresses) for _ in range(len(df))]

,Roll_Number,Student_Name,English,Maths,Biology,Chemistry,Physics,Computer_Applications,Attendance,Date_of_Birth,Phone_Number,Caste,Father_Name,Mother_Name,Family_Income_Per_Annum,Address
0,100,Kiaan Chakraborty,69,93,50,97,37,68,56,2008-12-14,3783359388,EWS,Chatura Parekh,Yadavi Gola,1623755,"Electronic City, Bangalore"
1,101,Tripti Cherian,68,62,74,39,71,48,85,2008-07-06,+915525393650,General,Bakhshi Wali,Dhriti Mann,1851649,"Rajajinagar, Bangalore"
2,102,Ria Chahal,98,74,69,89,87,36,79,2006-01-05,+913599880666,EWS,Ayush Bhargava,Anjali Das,958184,"Whitefield, Bangalore"
3,103,Adya Kade,45,55,42,83,49,71,73,2004-02-04,04235814550,SC,Gopal Munshi,Upadhriti Chaudhary,149863,"Indiranagar, Bangalore"
4,104,Kabir Lata,94,40,46,76,89,43,96,2005-01-03,+917272218871,EWS,Faris Bakshi,Charita Sankar,988679,"HSR Layout, Bangalore"

In [31]:
df.to_csv("academic_dataset.csv", index=False)
print("Addresses updated successfully!")

Addresses updated successfully!

In [32]:
len(df)

100

In [33]:
df.head()

,Roll_Number,Student_Name,English,Maths,Biology,Chemistry,Physics,Computer_Applications,Attendance,Date_of_Birth,Phone_Number,Caste,Father_Name,Mother_Name,Family_Income_Per_Annum,Address
0,100,Kiaan Chakraborty,69,93,50,97,37,68,56,2008-12-14,3783359388,EWS,Chatura Parekh,Yadavi Gola,1623755,"Electronic City, Bangalore"
1,101,Tripti Cherian,68,62,74,39,71,48,85,2008-07-06,+915525393650,General,Bakhshi Wali,Dhriti Mann,1851649,"Rajajinagar, Bangalore"
2,102,Ria Chahal,98,74,69,89,87,36,79,2006-01-05,+913599880666,EWS,Ayush Bhargava,Anjali Das,958184,"Whitefield, Bangalore"
3,103,Adya Kade,45,55,42,83,49,71,73,2004-02-04,04235814550,SC,Gopal Munshi,Upadhriti Chaudhary,149863,"Indiranagar, Bangalore"
4,104,Kabir Lata,94,40,46,76,89,43,96,2005-01-03,+917272218871,EWS,Faris Bakshi,Charita Sankar,988679,"HSR Layout, Bangalore"

In [34]:
df.columns

Index(['Roll_Number', 'Student_Name', 'English', 'Maths', 'Biology',
       'Chemistry', 'Physics', 'Computer_Applications', 'Attendance',
       'Date_of_Birth', 'Phone_Number', 'Caste', 'Father_Name', 'Mother_Name',
       'Family_Income_Per_Annum', 'Address'],
      dtype='object')

In [35]:
df.to_csv("academic_dataset.csv", index=False)

print("Academic Dataset saved successfully!")

Academic Dataset saved successfully!

In [36]:
import os

print(os.path.abspath("academic_dataset.csv"))

d:\aiml project\Academic_Dataset_Project\academic_dataset.csv

In [37]:
len(df)

100

In [1]:
import pandas as pd

df = pd.read_csv("academic_dataset.csv")
print(df.columns)

Index(['Roll_Number', 'Student_Name', 'English', 'Maths', 'Biology',
       'Chemistry', 'Physics', 'Computer_Applications', 'Attendance',
       'Date_of_Birth', 'Phone_Number', 'Caste', 'Father_Name', 'Mother_Name',
       'Family_Income_Per_Annum', 'Address'],
      dtype='object')

In [1]:
import pandas as pd

scholarship_data = {
    "Scholarship_Name": [
        "Merit Scholarship",
        "OBC Scholarship",
        "SC Scholarship",
        "EWS Scholarship",
        "Women Scholarship"
    ],

    "Min_Percentage": [
        80,
        60,
        60,
        70,
        75
    ]
}

df_scholarship = pd.DataFrame(scholarship_data)

df_scholarship.to_csv("scholarship_dataset.csv", index=False)

print(df_scholarship)

    Scholarship_Name  Min_Percentage
0  Merit Scholarship              80
1    OBC Scholarship              60
2     SC Scholarship              60
3    EWS Scholarship              70
4  Women Scholarship              75

In [2]:
import pandas as pd

scholarship_data = {
    "Scholarship_Name": [
        "Merit Scholarship",
        "National Merit Award",
        "SC Excellence Scholarship",
        "ST Education Grant",
        "OBC Support Scholarship",
        "EWS Financial Aid",
        "Women in STEM",
        "Rural Education Grant",
        "Top Performer Scholarship",
        "Science Excellence Award",
        "Engineering Talent Fund",
        "Future Leaders Scholarship",
        "Academic Star Award",
        "Bright Minds Scholarship",
        "Community Support Fund",
        "Higher Education Grant",
        "Innovation Scholarship",
        "Research Talent Award",
        "Need Based Scholarship",
        "Global Achievers Scholarship"
    ],

    "Min_Percentage": [
        90, 85, 60, 60, 65,
        70, 75, 55, 95, 80,
        85, 75, 88, 78, 60,
        70, 82, 90, 50, 92
    ],

    "Max_Income": [
        1000000, 800000, 400000, 400000, 500000,
        300000, 1000000, 250000, 1000000, 700000,
        600000, 500000, 900000, 400000, 250000,
        600000, 800000, 1000000, 200000, 1200000
    ],

    "Caste": [
        "Any", "Any", "SC", "ST", "OBC",
        "EWS", "Any", "Any", "Any", "Any",
        "Any", "Any", "Any", "Any", "Any",
        "Any", "Any", "Any", "Any", "Any"
    ]
}

df_scholarship = pd.DataFrame(scholarship_data)

df_scholarship.to_csv("scholarship_dataset.csv", index=False)

print("20 Scholarships Created Successfully!")
print(df_scholarship.head())

20 Scholarships Created Successfully!
            Scholarship_Name  Min_Percentage  Max_Income Caste
0          Merit Scholarship              90     1000000   Any
1       National Merit Award              85      800000   Any
2  SC Excellence Scholarship              60      400000    SC
3         ST Education Grant              60      400000    ST
4    OBC Support Scholarship              65      500000   OBC

In [3]:
print(len(df_scholarship))

20

In [6]:
import pandas as pd

# Load student dataset
students = pd.read_csv("academic_dataset.csv")

# Load scholarship dataset
scholarships = pd.read_csv("scholarship_dataset.csv")

# Select first student
for i in range(len(students)):
    
    student = students.iloc[i]

    total_marks = sum(student[sub] for sub in subjects)
    percentage = total_marks / len(subjects)

    if student["Family_Income_Per_Annum"] < 500000:
        print(
            student["Student_Name"],
            percentage,
            student["Family_Income_Per_Annum"],
            student["Caste"]
        )
        break

# Calculate percentage
subjects = [
    "English",
    "Maths",
    "Biology",
    "Chemistry",
    "Physics",
    "Computer_Applications"
]

total_marks = sum(student[sub] for sub in subjects)
percentage = total_marks / len(subjects)

print("Student Name:", student["Student_Name"])
print("Percentage:", round(percentage, 2))
print("Income:", student["Family_Income_Per_Annum"])
print("Caste:", student["Caste"])

print("\nEligible Scholarships:\n")

found = False

for _, scholarship in scholarships.iterrows():

    if (
        percentage >= scholarship["Min_Percentage"]
        and student["Family_Income_Per_Annum"] <= scholarship["Max_Income"]
        and (
            scholarship["Caste"] == "Any"
            or scholarship["Caste"] == student["Caste"]
        )
    ):
        print("✓", scholarship["Scholarship_Name"])
        found = True

if not found:
    print("❌ No Scholarship Eligible")

Adya Kade 57.5 149863 SC
Student Name: Adya Kade
Percentage: 57.5
Income: 149863
Caste: SC

Eligible Scholarships:

✓ Rural Education Grant
✓ Need Based Scholarship

In [7]:
import pandas as pd

scholarship_data = {
    "Scholarship_Name": [
        "Merit Scholarship",
        "National Merit Award",
        "SC Excellence Scholarship",
        "ST Education Grant",
        "OBC Support Scholarship",
        "EWS Financial Aid",
        "Women in STEM",
        "Rural Education Grant",
        "Top Performer Scholarship",
        "Science Excellence Award",
        "Engineering Talent Fund",
        "Future Leaders Scholarship",
        "Academic Star Award",
        "Bright Minds Scholarship",
        "Community Support Fund",
        "Higher Education Grant",
        "Innovation Scholarship",
        "Research Talent Award",
        "Need Based Scholarship",
        "Global Achievers Scholarship"
    ],

    "Min_Percentage": [
        90,85,60,60,65,
        70,75,55,95,80,
        85,75,88,78,60,
        70,82,90,50,92
    ],

    "Max_Income": [
        1000000,800000,400000,400000,500000,
        300000,1000000,250000,1000000,700000,
        600000,500000,900000,400000,250000,
        600000,800000,1000000,200000,1200000
    ],

    "Caste": [
        "Any","Any","SC","ST","OBC",
        "EWS","Any","Any","Any","Any",
        "Any","Any","Any","Any","Any",
        "Any","Any","Any","Any","Any"
    ],

    "Amount": [
        50000,40000,30000,30000,25000,
        35000,45000,20000,60000,50000,
        55000,30000,45000,35000,20000,
        30000,40000,50000,15000,70000
    ]
}

df = pd.DataFrame(scholarship_data)

df.to_csv("scholarship_dataset.csv", index=False)

print("Scholarship dataset updated successfully!")

Scholarship dataset updated successfully!